### PR TITLE
defined in mm instead of vox

### PR DESCRIPTION
**Pull request by jordandekraker**
this should be more robust to different input image resolutions. 52mm iso should be enough to cover the whole hippocampus.

### CODE REVIEW

**Comment by akhanf** [comment]
Isn't this a much smaller bounding box? (256 x 0.3mm = 76.8mm)

**Comment by jordandekraker** [comment]
I believe voxel size was relative to the input image, so in my case I had a 0.8mm being increased 400% to 0.2mm isotropic in the cropT1w, which worked out to 51.2mm. Just testing now so I'll confirm whether this is a good new default or not

**Comment by akhanf** [comment]
Ah yes forgot about that, yes you're right!

**Comment by jordandekraker** [comment]
while we're at it, i wonder if its worth setting a fixed voxel size, or maybe just making it relative to the `space-corobl`?

**Comment by akhanf** [comment]
I'm good with changing it to be a fixed size (rather than 400% relative), specified in a config file and/or cmd line arg?

**Comment by jordandekraker** [comment]
Great, I'll set that up right now! I'll keep the default to 0.2mm (or 0.3mm?) to minimize loss when rotating the corobl back to native (which is usually about 25-30deg sagittal rotation)

**Comment by akhanf** [comment]
yep I'm good with either one

**Review by akhanf — APPROVED** [review]

**Pull request merged**
