### PR TITLE
 Template-based segmentation, and new templates (marmoset, macaque) redo

### PR DESCRIPTION
**Pull request by akhanf**
This is a clean version of the https://github.com/khanlab/hippunfold/pull/264 PR. Should do some testing before this is merged in. Will need some doc updates too!
(messed up my other branch with a rebase, so this is a new PR)

TODO: add any relevant info that is in the other PR comments..

### CODE REVIEW

**Comment by akhanf** [comment]
btw, I'm going to generate dseg & coords on the CITI template (just running through hippunfold), so we can use that for template-based segmentation as well (as long as the dseg looks good)..

**Comment by akhanf** [comment]
ok this is good to test out now, I've enabled templateseg for MBMv3 and CITI168 templates

**Comment by jordandekraker** [comment]
My tests still won't run end-to-end. Specifically, the template injections steps in the `hemi-L` are generating volumes containing all 0. If I apply the injection warp myself via `ANTs` or if i shell into the container and warp with `greedy` then it works fine, but it won't work within the pipeline for some reason. 

Will look into it more next week

**Comment by akhanf** [comment]
Ah weird - what were your input args? I'll try from my end too. I tested templateseg with mbmv3 and citi168 and was working fine.

________________________________

**Comment by jordandekraker** [comment]
```
python hippunfold/run.py . test_mac2 participant --modality T1w --template CIVM --use-template-seg --path-T1w /data/mica1/03_projects/neichert/hipmac/bids/{subject}/anat/struct_brain_restore_gibbs.nii.gz --use-singularity --keep-going --rerun-incomplete --cores 24
```
the input is one from the closed dataset that Nicole used in her project

**Comment by akhanf** [comment]
Ah OK- I'll try it out on an openly available macaque dataset tomorrow. Could be the template voxel spacing, as I set that with cli when using marm template. It's something we could pre-configure if so...

**Comment by akhanf** [comment]
Looks like that is actually an ex vivo macaque template -- I don't have an ex vivo macaque dataset to try it out on, and it might have limited utility for in vivo data (the couple scans I tried failed linear registration)..  I am assuming the dataset you are applying it to is an ex vivo scan?

**Comment by jordandekraker** [comment]
ahh haha that perfectly explains the error i was getting - when i applied the segmentation manually i of course used the correct template file!
Good catch. Still waiting for my test case to complete, but it looks good so far!

**Comment by jordandekraker** [comment]
My test case worked, I think this is ready to merge save for the Docs error...

**Comment by jordandekraker** [comment]
I believe that some of the issues that arise in registering in-vivo to ex-vivo (or vice versa) are due to skull-stripping. An easy fix is to add the `--rigid_reg_template` flag, and the deformable registration is performed in cropped space so doesn't suffer from this issue! I tested this in MBMv3 with `--template MBMv2` 
image

**Comment by akhanf** [comment]
Great! We could merge this in then and do doc updates in another PR

**Comment by akhanf** [comment]
I see the recent flurry of activity @jordandekraker ! Would be great to resolve this PR too -- let me have a look to see what is failing the tests, I think we are good to merge after that is done, right?

**Comment by jordandekraker** [comment]
Haha yes, just got back from a conference and wanted to clean things up a bit. I forget the issue that I was having here, but i have no uncommitted changes or notes. The soonest I can get to it will probably be Friday

**Comment by akhanf** [comment]
Sorted out what was causing the tests to fail - the edits to preproc_t2.smk you made in #288 overrode some required changes in this branch related to downloading template files.. Not sure how that happened but could be because of that branch was based off something else.. 

Anyways, probably worth giving this a "wet"-run before we merge in, I'll run something now

**Comment by jordandekraker** [comment]
My "wet"-run succeeded!

I also have a local commit to add the Allen Mouse Brain. The only changes are in snakebids.yml to provide the new template and better descriptions. The OSF link is still blank since I wasn't sure whether to make this public yet.

I did notice that the ABA template fails in some other mouse brains still (its very detailed and typical scans don't have this level of contrast). so the ABA template, and probably the macaque and marmoset templates, could probably all use a bit of benchmarking. 

Maybe we can meet soon along with @Bradley-Karat to discuss?

**Comment by jordandekraker** [comment]
OK should be ready for merge!

**Comment by akhanf** [comment]
great! I'll merge it in now.. note, before we do a versioned release, we should have something to deal with the fact that the workflow now requires internet -- e.g. have a `--download-only` flag that when enabled simply downloads any external resources required for the run. Should be easy to implement I think, I'll have a go in another PR..

**Pull request merged**
