### PR TITLE
simple version for non-contributors

### PR DESCRIPTION
**Pull request by jordandekraker**

### CODE REVIEW

**Review by akhanf — APPROVED** [review]
Looks good to me, feel free to merge in. I've enable docs on this branch here: https://hippunfold.readthedocs.io/en/simplifiedinstall/index.html if you want to take a look before merging

**Comment by jordandekraker** [comment]
For some reason these sections are not showing up in readthedocs: https://github.com/khanlab/hippunfold/tree/simplifiedinstall/docs/usage

**Comment by akhanf** [comment]
ah good catch, looks like I broke those when converting to markdown -- I've reverted the two usage CLI doc files to RST to get it working again, let's see if that fixes it --

**Comment by akhanf** [comment]
ok they're back, but I noticed there is a bug in grabbing the hippunfold CLI options, looks like it is something that broke with snakebids, I will need to look into that..

**Comment by jordandekraker** [comment]
Nice yeah its back now, but the Command line interface page still looks funny - its showing the snakebids workflows instead of hippunfold options

**Comment by akhanf** [comment]
ok actually was able to fix it by making a change to the `run.py` - so all good to go now I think

**Pull request merged**
