### PR TITLE
began new unfolded ref space for DG

### PR DESCRIPTION
**Pull request by jordandekraker**
This still needs to regenerate the files in resources/unfold_template_autotopDG

### CODE REVIEW

**Comment by jordandekraker** [comment]
@akhanf would you be able to rerun https://github.com/khanlab/hippunfold/blob/master/gen_unfold_template/Snakefile to generate the files in https://github.com/khanlab/hippunfold/tree/dentate/hippunfold/resources/unfold_template_autotopDG using the reference space generated in this branch? You have the reference surfaces (UR100 from hippunfold v0.5.1). Should also make sure this branch is up-to-date with `dentate`

**Comment by akhanf** [comment]
yep should be able to do that some point this week

**Comment by akhanf** [comment]
I'm a bit confused with the branching -- do you want to make use of the latest commits in the `dentate` branch? If so, we should just merge this branch into that..

**Comment by jordandekraker** [comment]
Yeah i just made this branch so i could test stuff in the other branch without these changes stopping it. I'm pretty much satisfied with things in the other branch so we could merge them now

**Pull request merged**
