### PR TITLE
Added documentation, and reorganized giftis

### PR DESCRIPTION
**Pull request by akhanf**
- gifti naming now more bids-like
- added a bunch of documentation
- cleaning up snakebids.yml config
- replaced hardcoded containers in config with docker URIs

### CODE REVIEW

**Comment by akhanf** [comment]
@royhaast @jordandekraker : have simplified the gifti naming a bit see details in the message for "renamed and reorganized surf gifti files" above..  

The documentation now reflects this too. Let me know if this looks fine and I'll merge it in.

The other change to be aware of is I removed the hardcoding of singularity paths on graham -- so now when you run the workflow on graham, you need to use the `--singularity-prefix=/project/6050199/akhanf/singularity/snakemake_container` option so it can find the containers -- Note that this is automatically done in cc-slurm, but if you run without cc-slurm you'll need that option (i.e. if you are doing something on an interactive node)..

**Comment by akhanf** [comment]
merged this in to get the new docs and docker build going

**Comment by jordandekraker** [comment]
This is merged already, but I wanted to bring up a bug i'm getting running from the new master branch (using `--profile cc-slurm`):
```
[Fri Jan 29 12:38:24 2021]
rule n4_t2:
    input: work/sub-001/anat/sub-001_run-2_T2w.nii.gz
    output: work/sub-001/anat/sub-001_run-2_desc-n4_T2w.nii.gz
    jobid: 9
    wildcards: subject=001, run=2
    threads: 8
    resources: mem_mb=4000

Activating singularity image /project/ctb-akhanf/akhanf/singularity/snakemake_containers/046070418f7e42466e98b219fc06fd7e.simg
Exception caught during reference file reading 

itk::ImageFileReaderException (0x38512d0)
Location: "unknown" 
File: /src/ants/build/ITKv5-install/include/ITK-5.0/itkImageFileReader.hxx
Line: 142
Description:  Could not create IO object for reading file work/sub-001/anat/sub-001_T1w.nii.gz
  Tried to create one of the following:
    BMPImageIO
    BioRadImageIO
    Bruker2dseqImageIO
    GDCMImageIO
    GE4ImageIO
    GE5ImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    LSMImageIO
    MGHImageIO
    MINCImageIO
    MRCImageIO
    MetaImageIO
    NiftiImageIO
    NrrdImageIO
    PNGImageIO
    StimulateImageIO
    TIFFImageIO
    VTKImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.


 file work/sub-001/anat/sub-001_T1w.nii.gz
Exception caught during reference file reading 

itk::ImageFileReaderException (0x22122e0)
Location: "unknown" 
File: /src/ants/build/ITKv5-install/include/ITK-5.0/itkImageFileReader.hxx
Line: 142
Description:  Could not create IO object for reading file work/sub-001/anat/sub-001_run-2_T2w.nii.gz
  Tried to create one of the following:
    BMPImageIO
    BioRadImageIO
    Bruker2dseqImageIO
    GDCMImageIO
    GE4ImageIO
    GE5ImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    LSMImageIO
    MGHImageIO
    MINCImageIO
    MRCImageIO
    MetaImageIO
    NiftiImageIO
    NrrdImageIO
    PNGImageIO
    StimulateImageIO
    TIFFImageIO
    VTKImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.


 file work/sub-001/anat/sub-001_run-2_T2w.nii.gz
/bin/bash: line 1: 147004 Segmentation fault      (core dumped) ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8 N4BiasFieldCorrection -d 3 -i work/sub-001/anat/sub-001_run-2_T2w.nii.gz -o work/sub-001/anat/sub-001_run-2_desc-n4_T2w.nii.gz
/bin/bash: line 1: 147005 Segmentation fault      (core dumped) ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8 N4BiasFieldCorrection -d 3 -i work/sub-001/anat/sub-001_T1w.nii.gz -o results/sub-001/anat/sub-001_desc-preproc_T1w.nii.gz
[Fri Jan 29 12:38:26 2021]
Error in rule n4_t2:
[Fri Jan 29 12:38:26 2021]
    jobid: 9
Error in rule n4_t1:
    output: work/sub-001/anat/sub-001_run-2_desc-n4_T2w.nii.gz
    jobid: 16
    shell:
        ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8 N4BiasFieldCorrection -d 3 -i work/sub-001/anat/sub-001_run-2_T2w.nii.gz -o work/sub-001/anat/sub-001_run-2_desc-n4_T2w.nii.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    output: results/sub-001/anat/sub-001_desc-preproc_T1w.nii.gz

    shell:
        ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8 N4BiasFieldCorrection -d 3 -i work/sub-001/anat/sub-001_T1w.nii.gz -o results/sub-001/anat/sub-001_desc-preproc_T1w.nii.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message```

**Comment by akhanf** [comment]
that segfault looks odd -- the command and container snakemake is using is correct, so I am wondering if maybe some filesystem error caused the T1w file to be corrupted or incomplete when first written? Does this error happen when you re-run or run for another subject?

**Comment by jordandekraker** [comment]
Aha yes I can see the size of the T1w.nii.gz is 0bytes. If you intended to keep this file as a test case (hippunfold/test_data/) in this git repo then I think you'll have to use `git lfs`

**Comment by akhanf** [comment]
ah no those are just dry run test cases, to test the workflow with `-np` -- useful to make sure the workflow is working properly without having to actually run any rules

**Comment by akhanf** [comment]
i.e. they are meant to be 0 bytes

**Comment by jordandekraker** [comment]
gotcha! thanks

**Pull request merged**
