### PR TITLE
workflow updates to allow T2w without T1w

### PR DESCRIPTION
**Pull request by akhanf**
Wanted to try hippunfold on some HSG data today (no T1w image), but there wasn't a nice way to do that currently, so I made these workflow updates to add rule for registration, then it actually wasn't that much more work to go all the way and make the native space generic to either T1w or T2w. Will test things out a bit more extensively, but the dry-run seems to be doing fine.. I think this will be useful for alot of users, @jordandekraker you probably have some data already you can test this on? We can also think about streamlining the CLI options a bit more if it works well (e.g. making reg_t2_to_template the default when modality==T2w..)

Changes:
- adds a reg_t2_to_template rule
- adds T2w CITI168 template image for this rule
- adds a --reg_t2_to_template CLI option to enable this rule (otherwise
default behaviour is to use T1w as usual)
- add a {native_modality} wildcard so rules that register or resample to
cropT1w/T1w space are now generic
- adds cropT2w to possible output_spaces
- in order to run T2w-only workflow, just need to specify:
`--reg_t2_to_template --output_spaces cropT2w`
- working with dry-run, and some initial testing on HSG data

TODO: 
- [x] test entire workflow on real data
- [x] make sure all dry-run testing works
- [x] add more dry-run test cases
- [x] update the documentation
- [x] revisit CLI names

### CODE REVIEW

**Comment by jordandekraker** [comment]
Good idea.

One more TODO: 

- [ ] update the 'No T1w images' section of the tutorials docs (https://github.com/khanlab/hippunfold/blob/master/docs/tutorials/standardBIDS.md#no-t1w-images)

I'll give this branch a test today

**Comment by akhanf** [comment]
I'm a bit wary of adjusting the workflow automatically based on the available bids data for those same reasons, and the possibility that the workflow does something unintended by the user.. 

But I am thinking we could just make registration with T2 the default for {T2w,segT2w} workflows, e.g. instead of the `--reg_t2_to_template` option, we could have a `--template_reg_modality` option that can be used to override this to `T1w`.. 

Also, we could perhaps have the possible output_spaces options be {cropnative,corobl} instead {cropT1w,cropT2w,corobl}, and have the workflow set variables automatically so the user doesn't have to additionally change this option when selecting modality..

**Comment by jordandekraker** [comment]
OK that makes sense to me! 

One other thought: I wonder if we should consider dropping the `--output_spaces` and simply leave it as `cropnative`?  `corobl` will always live in the `work` dir, and part of the reason I initially wanted it was just for when a cropped image was used as input (eg `--modality cropseg`) but I think that's already handled fine now. 
Just thinking about ways to simplify things for the user!

**Comment by akhanf** [comment]
I see what you mean, but I think it's better to keep it in case we want to add more functionality, e.g. having options for bold or dwi..  It can be an option that the user doesn't need to worry about though, so we could perhaps leave it out of the higher-level documentation since the default would produce the desired result almost all of the time.. 

Another option I am wondering about is `--rigid_reg_template` -- this is basically required when we have reduced FOV data, as it fails badly if not.. I am wondering how it might affect things if we just make this option the default? (e.g. replace it with a `--use_affine_reg_to_template` that is disabled by default)?

**Comment by jordandekraker** [comment]
OK sounds good. After this PR I'll make a few updates to the example Tutorials. 

I think we want affine to be the default for registering to the CITI template, but I could be convinced that rigid is better

**Comment by akhanf** [comment]
I agree affine is probably preferred for whole brain data .. maybe we can just call the `--rigid_reg_template` option something like `--reduced_fov` to make it clear this must be used when using reduced FOV data?

**Comment by akhanf** [comment]
ok I made some CLI changes, let me know what you think..

**Comment by jordandekraker** [comment]
Yeah this looks great! I'll make some updates to the tutorials and commit them before we merge

**Comment by jordandekraker** [comment]
OK i made some basic updates. The docs will still need a few updates to include things like images of DG surfaces and changes to filenames, as in https://github.com/khanlab/hippunfold/issues/127, but I think this should cover everything in the current PR

**Comment by akhanf** [comment]
We can continue to make minor/patch releases afterwards (for docs, minor updates etc), but should try to have the major breaking changes in this v1.0.0 release

**Comment by jordandekraker** [comment]
Agreed!

**Pull request merged**
