### PR TITLE
fast laplace via initialization

### PR DESCRIPTION
**Pull request by jordandekraker**
I recycled some old matlab code to get a fast (and good quality) initialization for the lapalce solver. Only dependency is scikit-fmm which is pretty light.
This could be used in conjunction with image pyramids as in https://github.com/khanlab/hippunfold/issues/85, but honestly I think this is fast enough now. 

Tested and working on my end!

### CODE REVIEW

**Review by akhanf — COMMENTED** [review]
I don't know if its a great idea to make this combined initialization the new default.. 
The combination is not really principled by just averaging them together.. I think it would be more sensible to have an option to select the initialization type.

**Comment by jordandekraker** [comment]
Could also just keep the forward or the backward. The only problem is the end point from one direction doesn't match the start point from the other, so I wanted the combination to be weighted more heavily towards the start of each march. If that's too complicated then just one of the two marches would still be a good initialization

**Comment by jordandekraker** [comment]
Now that I think about it, if i want to weight their combination, then maybe I should flip them both, square them, flip one back, average them, and then square root the whole thing.

Whatever the combination method is (just using one direction, averaging them, or doing a weighted average) is still a huge improvement over just initializing with a value of 0.5, and so choosing a combination method is a pretty minor change in comparison.

**Comment by akhanf** [comment]
Sorry I may have misunderstood the change when I glanced over it, I thought
you were averaging the injected coords with fast marching coords?

**Comment by jordandekraker** [comment]
Nope, this is only for when there is not shape injection (and therefore no initialization injection).

**Comment by jordandekraker** [comment]
Did some quick testing and just averaging the forward and backward march seems to consistently do best (weighting averaging was getting very complicated). Can probably merge anytime

**Review by akhanf — APPROVED** [review]

**Pull request merged**
